/*2016*/
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-01-01', 'AÑO NUEVO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-01-11', 'DIA DE LOS REYES MAGOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-03-20', 'DOMINGO DE RAMOS', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-03-21', 'DIA DE SAN JOSE', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-03-24', 'JUEVES SANTO', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-03-25', 'VIERNES SANTO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-03-27', 'DOMINGO DE RESURRECCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-05-01', 'DIA DEL TRABAJO', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-05-09', 'DIA DE LA ASCENCION', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-05-30', 'CORPUS CHRISTI', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-06-06', 'SAGRADO CORAZON', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-07-04', 'SAN PEDRO Y SAN PABLO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-07-20', 'DIA DE LA INDEPENDENCIA', 'WED');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-08-07', 'BATALLA DE BOYACA', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-08-15', 'LA ASUNCION DE LA VIRGEN', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-10-17', 'DIA DE LA RAZA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-11-07', 'TODOS LOS SANTOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-11-14', 'INDEPENDENCIA DE CARTAGENA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-12-08', 'DIA DE LA INMACULADA CONCEPCION', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2016-12-25', 'DIA DE NAVIDAD', 'SUN');
/*2017*/
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-01-01', 'AÑO NUEVO', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-01-09', 'DIA DE LOS REYES MAGOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-03-20', 'DIA DE SAN JOSE', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-04-09', 'DOMINGO DE RAMOS', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-04-13', 'JUEVES SANTO', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-04-14', 'VIERNES SANTO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-04-16', 'DOMINGO DE RESURRECCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-05-01', 'DIA DEL TRABAJO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-05-29', 'DIA DE LA ASCENCION', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-06-19', 'CORPUS CHRISTI', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-06-26', 'SAGRADO CORAZON', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-07-03', 'SAN PEDRO Y SAN PABLO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-07-20', 'DIA DE LA INDEPENDENCIA', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-08-07', 'BATALLA DE BOYACA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-08-21', 'LA ASUNCION DE LA VIRGEN', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-10-16', 'DIA DE LA RAZA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-11-06', 'TODOS LOS SANTOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-11-13', 'INDEPENDENCIA DE CARTAGENA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-12-08', 'DIA DE LA INMACULADA CONCEPCION', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2017-12-25', 'DIA DE NAVIDAD', 'MON');
/*2018*/
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-01-01', 'AÑO NUEVO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-01-08', 'DIA DE LOS REYES MAGOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-03-19', 'DIA DE SAN JOSE', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-03-25', 'DOMINGO DE RAMOS', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-03-29', 'JUEVES SANTO', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-03-30', 'VIERNES SANTO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-04-01', 'DOMINGO DE RESURRECCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-05-01', 'DIA DEL TRABAJO', 'TUE');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-05-14', 'DIA DE LA ASCENCION', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-06-04', 'CORPUS CHRISTI', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-06-11', 'SAGRADO CORAZON', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-07-02', 'SAN PEDRO Y SAN PABLO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-07-20', 'DIA DE LA INDEPENDENCIA', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-08-07', 'BATALLA DE BOYACA', 'TUE');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-08-20', 'LA ASUNCION DE LA VIRGEN', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-10-15', 'DIA DE LA RAZA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-11-05', 'TODOS LOS SANTOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-11-12', 'INDEPENDENCIA DE CARTAGENA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-12-08', 'DIA DE LA INMACULADA CONCEPCION', 'SAT');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2018-12-25', 'DIA DE NAVIDAD', 'TUE');
/*2019*/
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-01-01', 'AÑO NUEVO', 'TUE');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-01-07', 'DIA DE LOS REYES MAGOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-03-25', 'DIA DE SAN JOSE', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-04-14', 'DOMINGO DE RAMOS', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-04-18', 'JUEVES SANTO', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-04-19', 'VIERNES SANTO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-04-21', 'DOMINGO DE RESURRECCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-05-01', 'DIA DEL TRABAJO', 'WED');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-06-03', 'DIA DE LA ASCENCION', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-06-24', 'CORPUS CHRISTI', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-07-01', 'SAGRADO CORAZON', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-07-01', 'SAN PEDRO Y SAN PABLO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-07-20', 'DIA DE LA INDEPENDENCIA', 'SAT');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-08-07', 'BATALLA DE BOYACA', 'WED');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-08-19', 'LA ASUNCION DE LA VIRGEN', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-10-14', 'DIA DE LA RAZA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-11-04', 'TODOS LOS SANTOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-11-11', 'INDEPENDENCIA DE CARTAGENA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-12-08', 'DIA DE LA INMACULADA CONCEPCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2019-12-25', 'DIA DE NAVIDAD', 'WED');
/*2020*/
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-01-01', 'AÑO NUEVO', 'WED');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-01-06', 'DIA DE LOS REYES MAGOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-03-23', 'DIA DE SAN JOSE', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-04-05', 'DOMINGO DE RAMOS', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-04-09', 'JUEVES SANTO', 'THU');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-04-10', 'VIERNES SANTO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-04-12', 'DOMINGO DE RESURRECCION', 'SUN');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-05-01', 'DIA DEL TRABAJO', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-05-25', 'DIA DE LA ASCENCION', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-06-15', 'CORPUS CHRISTI', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-06-22', 'SAGRADO CORAZON', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-06-29', 'SAN PEDRO Y SAN PABLO', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-07-20', 'DIA DE LA INDEPENDENCIA', 'SAT');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-08-07', 'BATALLA DE BOYACA', 'FRI');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-08-17', 'LA ASUNCION DE LA VIRGEN', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-10-12', 'DIA DE LA RAZA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-11-02', 'TODOS LOS SANTOS', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-11-16', 'INDEPENDENCIA DE CARTAGENA', 'MON');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-12-08', 'DIA DE LA INMACULADA CONCEPCION', 'TUE');
INSERT INTO TableName(holiday, description, weekday) VALUES ('2020-12-25', 'DIA DE NAVIDAD', 'FRI');

